import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const localesDir = path.join(__dirname, '../src/locales');

const translations = {
    "zh-TW": { "title": "幫助中心", "subtitle": "快速了解如何使用 ListenMate++", "library_title": "📚 資料庫", "library_desc": "匯入本機音訊檔案或透過 URL（YouTube/Bilibili）下載音訊。點擊「繼續學習」進入學習工作區。", "workspace_title": "🎧 聽讀訓練", "workspace_desc": "播放音訊並查看字幕。點擊任意單字可跳轉到對應時間點。選取文字後點擊「跟讀」可進行口語練習。設定 AB 段可反覆練習難點。", "speaking_title": "🎤 口語跟讀", "speaking_desc": "點擊「直接朗讀」後大聲讀出參考原句，AI 將轉錄您的錄音並與原文逐詞比對，給出發音得分。", "review_title": "📅 複習任務", "review_desc": "系統根據艾賓浩斯遺忘曲線自動安排每次聽寫的複習時間，幫助您鞏固學習成果。", "shortcuts_title": "⌨️ 快速鍵", "shortcut_space": "播放 / 暫停", "shortcut_left": "後退 5 秒", "shortcut_right": "前進 5 秒", "faq_title": "常見問題", "shortcut_f_a_q": "常見問題", "faq_blackscreen": "黑屏/白屏：請確保已安裝 WebView2 執行階段。", "faq_ytdlp": "URL 下載失敗：請檢查 yt-dlp 是否安裝（pip install yt-dlp）。" },
    "ja": { "title": "ヘルプセンター", "subtitle": "ListenMate++ のクイックガイド", "library_title": "📚 ライブラリ", "library_desc": "ローカルの音声ファイルをインポートするか、URL（YouTube/Bilibili）経由で音声をダウンロードします。「学習を続ける」をクリックしてワークスペースに入ります。", "workspace_title": "🎧 学習ワークスペース", "workspace_desc": "音声を再生し、字幕を表示します。単語をクリックするとそのタイムスタンプにジャンプします。テキストを選択して「シャドーイング」をクリックするとスピーキングの練習ができます。AB区間を設定して難しい箇所を繰り返し練習できます。", "speaking_title": "🎤 スピーキング練習", "speaking_desc": "「音読」をクリックして参考文を声に出して読みます。AIが録音を文字起こしし、単語ごとに比較して発音スコアを出します。", "review_title": "📅 復習タスク", "review_desc": "システムはエビングハウスの忘却曲線に基づいて復習スケジュールを自動的に設定し、学習内容の定着をサポートします。", "shortcuts_title": "⌨️ キーボードショートカット", "shortcut_space": "再生 / 一時停止", "shortcut_left": "5秒戻る", "shortcut_right": "5秒進む", "faq_title": "よくある質問", "shortcut_f_a_q": "よくある質問", "faq_blackscreen": "真っ黒/真っ白な画面: 最新のWebView2ランタイムをインストールしてください。", "faq_ytdlp": "URLダウンロード失敗: yt-dlpがインストールされているか確認してください（pip install yt-dlp）。" },
    "ko": { "title": "도움말 센터", "subtitle": "ListenMate++ 빠른 안내서", "library_title": "📚 라이브러리", "library_desc": "로컬 오디오 파일을 가져오거나 URL(YouTube/Bilibili)을 통해 오디오를 다운로드합니다. '학습 계속하기'를 클릭하여 학습 작업 공간으로 들어갑니다.", "workspace_title": "🎧 학습 작업 공간", "workspace_desc": "오디오를 재생하고 스크립트를 봅니다. 단어를 클릭하면 해당 타임스탬프로 이동합니다. 텍스트를 선택하고 '섀도잉'을 클릭하여 말하기 연습을 합니다. AB 구간을 설정하여 어려운 부분을 반복 연습하세요.", "speaking_title": "🎤 말하기 연습", "speaking_desc": "'소리 내어 읽기'를 클릭하고 참고 문장을 소리 내어 말하세요. AI가 녹음을 전사하고 단어별로 비교하여 발음 점수를 제공합니다.", "review_title": "📅 복습 작업", "review_desc": "시스템은 에빙하우스 망각 곡선에 따라 자동으로 복습 세션을 예약하여 학습한 내용을 통합하도록 돕습니다.", "shortcuts_title": "⌨️ 키보드 단축키", "shortcut_space": "재생 / 일시정지", "shortcut_left": "5초 뒤로", "shortcut_right": "5초 앞으로", "faq_title": "자주 묻는 질문", "shortcut_f_a_q": "자주 묻는 질문", "faq_blackscreen": "검은색/흰색 화면: 최신 WebView2 런타임을 설치하십시오.", "faq_ytdlp": "URL 다운로드 실패: yt-dlp가 설치되어 있는지 확인하십시오(pip install yt-dlp)." },
    "ru": { "title": "Справочный центр", "subtitle": "Краткое руководство по ListenMate++", "library_title": "📚 Библиотека", "library_desc": "Импортируйте локальные аудиофайлы или загружайте аудио по URL (YouTube/Bilibili). Нажмите «Продолжить», чтобы войти в рабочее пространство.", "workspace_title": "🎧 Рабочее пространство", "workspace_desc": "Воспроизводите аудио и просматривайте стенограммы. Нажмите на любое слово, чтобы перейти к этой отметке времени. Выделите текст и нажмите «Следование», чтобы попрактиковаться в разговорной речи. Задавайте отрезки AB для повторения сложных фрагментов.", "speaking_title": "🎤 Практика речи", "speaking_desc": "Нажмите «Прочитать вслух» и произнесите эталонное предложение. ИИ расшифрует вашу запись, сравнит ее пословно и выдаст оценку произношения.", "review_title": "📅 Задачи на повторение", "review_desc": "Система автоматически планирует сеансы повторения на основе кривой забывания Эббингауза, чтобы помочь вам закрепить изученное.", "shortcuts_title": "⌨️ Сочетания клавиш", "shortcut_space": "Воспроизведение / Пауза", "shortcut_left": "Назад на 5 секунд", "shortcut_right": "Вперед на 5 секунд", "faq_title": "Часто задаваемые вопросы", "shortcut_f_a_q": "Часто задаваемые вопросы", "faq_blackscreen": "Черный/белый экран: пожалуйста, установите последнюю версию WebView2 Runtime.", "faq_ytdlp": "Ошибка загрузки URL: убедитесь, что установлен yt-dlp (pip install yt-dlp)." },
    "pt": { "title": "Centro de Ajuda", "subtitle": "Guia rápido para usar o ListenMate++", "library_title": "📚 Biblioteca", "library_desc": "Importe arquivos de áudio locais ou baixe áudio via URL (YouTube/Bilibili). Clique em \"Continuar\" para entrar no espaço de estudo.", "workspace_title": "🎧 Espaço de Estudo", "workspace_desc": "Reproduza áudio e veja as transcrições. Clique em qualquer palavra para pular para aquele timestamp. Selecione o texto e clique em \"Shadow\" para praticar a fala. Defina segmentos AB para repetir passagens difíceis.", "speaking_title": "🎤 Prática de Fala", "speaking_desc": "Clique em \"Ler em voz alta\" e diga a frase de referência. A IA irá transcrever sua gravação, compará-la palavra por palavra e dar a você uma pontuação de pronúncia.", "review_title": "📅 Tarefas de Revisão", "review_desc": "O sistema agenda automaticamente sessões de revisão com base na curva de esquecimento de Ebbinghaus para ajudar a consolidar o que você aprendeu.", "shortcuts_title": "⌨️ Atalhos de Teclado", "shortcut_space": "Reproduzir / Pausar", "shortcut_left": "Voltar 5 segundos", "shortcut_right": "Avançar 5 segundos", "faq_title": "Perguntas Frequentes", "shortcut_f_a_q": "Perguntas Frequentes", "faq_blackscreen": "Tela preta/branca: Por favor, instale o WebView2 Runtime mais recente.", "faq_ytdlp": "Falha no download da URL: Certifique-se de que o yt-dlp está instalado (pip install yt-dlp)." },
    "es": { "title": "Centro de Ayuda", "subtitle": "Guía rápida para ListenMate++", "library_title": "📚 Biblioteca", "library_desc": "Importa archivos de audio locales o descarga audio a través de URL (YouTube/Bilibili). Haz clic en \"Continuar\" para entrar al espacio de estudio.", "workspace_title": "🎧 Espacio de Estudio", "workspace_desc": "Reproduce audio y visualiza transcripciones. Haz clic en cualquier palabra para saltar a esa marca de tiempo. Selecciona texto y haz clic en \"Shadow\" para practicar el habla. Configura segmentos AB para repetir pasajes difíciles.", "speaking_title": "🎤 Práctica de Habla", "speaking_desc": "Haz clic en \"Leer en voz alta\" y di la frase de referencia. La IA transcribirá tu grabación, la comparará palabra por palabra y te dará una puntuación de pronunciación.", "review_title": "📅 Tareas de Repaso", "review_desc": "El sistema programa automáticamente sesiones de repaso basadas en la curva del olvido de Ebbinghaus para ayudarte a consolidar lo aprendido.", "shortcuts_title": "⌨️ Atajos de Teclado", "shortcut_space": "Reproducir / Pausar", "shortcut_left": "Retroceder 5 segundos", "shortcut_right": "Avanzar 5 segundos", "faq_title": "Preguntas Frecuentes", "shortcut_f_a_q": "Preguntas Frecuentes", "faq_blackscreen": "Pantalla negra/blanca: Instala el último WebView2 Runtime.", "faq_ytdlp": "Fallo de descarga de URL: Asegúrate de que yt-dlp esté instalado (pip install yt-dlp)." },
    "fr": { "title": "Centre d'aide", "subtitle": "Guide rapide de ListenMate++", "library_title": "📚 Bibliothèque", "library_desc": "Importez des fichiers audio locaux ou téléchargez de l'audio via URL (YouTube/Bilibili). Cliquez sur « Continuer » pour accéder à l'espace d'étude.", "workspace_title": "🎧 Espace d'étude", "workspace_desc": "Lisez l'audio et affichez les transcriptions. Cliquez sur n'importe quel mot pour accéder à cet horodatage. Sélectionnez du texte et cliquez sur « Shadowing » pour pratiquer l'oral. Définissez des segments AB pour répéter des passages difficiles.", "speaking_title": "🎤 Pratique de l'oral", "speaking_desc": "Cliquez sur « Lire à voix haute » et prononcez la phrase de référence. L'IA transcrira votre enregistrement, le comparera mot par mot et vous attribuera un score de prononciation.", "review_title": "📅 Tâches de révision", "review_desc": "Le système planifie automatiquement des sessions de révision basées sur la courbe de l'oubli d'Ebbinghaus pour vous aider à consolider vos acquis.", "shortcuts_title": "⌨️ Raccourcis clavier", "shortcut_space": "Lecture / Pause", "shortcut_left": "Reculer de 5 secondes", "shortcut_right": "Avancer de 5 secondes", "faq_title": "FAQ", "shortcut_f_a_q": "FAQ", "faq_blackscreen": "Écran noir/blanc : Veuillez installer le dernier WebView2 Runtime.", "faq_ytdlp": "Échec du téléchargement d'URL : Vérifiez que yt-dlp est installé (pip install yt-dlp)." },
    "de": { "title": "Hilfezentrum", "subtitle": "Kurzanleitung für ListenMate++", "library_title": "📚 Bibliothek", "library_desc": "Importieren Sie lokale Audiodateien oder laden Sie Audio über eine URL (YouTube/Bilibili) herunter. Klicken Sie auf „Weiter“, um den Lernarbeitsbereich zu betreten.", "workspace_title": "🎧 Lernarbeitsbereich", "workspace_desc": "Spielen Sie Audio ab und zeigen Sie Transkripte an. Klicken Sie auf ein beliebiges Wort, um zu diesem Zeitstempel zu springen. Markieren Sie Text und klicken Sie auf „Shadowing“, um das Sprechen zu üben. Legen Sie AB-Abschnitte fest, um schwierige Passagen zu wiederholen.", "speaking_title": "🎤 Sprechübung", "speaking_desc": "Klicken Sie auf „Laut vorlesen“ und sprechen Sie den Referenzsatz. Die KI transkribiert Ihre Aufnahme, vergleicht sie Wort für Wort und gibt Ihnen eine Aussprachebewertung.", "review_title": "📅 Wiederholungsaufgaben", "review_desc": "Das System plant automatisch Wiederholungssitzungen basierend auf der Ebbinghaus-Vergessenskurve, um Ihnen zu helfen, das Gelernte zu festigen.", "shortcuts_title": "⌨️ Tastaturkürzel", "shortcut_space": "Wiedergabe / Pause", "shortcut_left": "5 Sekunden zurück", "shortcut_right": "5 Sekunden vor", "faq_title": "Häufig gestellte Fragen", "shortcut_f_a_q": "FAQ", "faq_blackscreen": "Schwarzer/weißer Bildschirm: Bitte installieren Sie die neueste WebView2 Runtime.", "faq_ytdlp": "URL-Download fehlgeschlagen: Bitte stellen Sie sicher, dass yt-dlp installiert ist (pip install yt-dlp)." },
    "ar": { "title": "مركز المساعدة", "subtitle": "دليل سريع لاستخدام ListenMate++", "library_title": "📚 المكتبة", "library_desc": "استيراد ملفات صوتية محلية أو تنزيل ملفات صوتية عبر الرابط (YouTube/Bilibili). انقر على \"متابعة\" للدخول إلى مساحة الدراسة.", "workspace_title": "🎧 مساحة الدراسة", "workspace_desc": "تشغيل الصوت وعرض النصوص. انقر على أي كلمة للانتقال إلى ذلك الوقت. حدد النص وانقر على \"ترديد\" للتدرب على التحدث. تعيين مقاطع AB لتكرار المقاطع الصعبة.", "speaking_title": "🎤 ممارسة التحدث", "speaking_desc": "انقر على \"قراءة بصوت عالٍ\" وقل الجملة المرجعية. ستقوم ميزة الذكاء الاصطناعي بنسخ تسجيلك الصوتي ومقارنته كلمة بكلمة، وإعطائك درجة في النطق.", "review_title": "📅 مهام المراجعة", "review_desc": "يجدول النظام جلسات المراجعة تلقائيًا استنادًا إلى منحنى النسيان لإبنجهاوس لمساعدتك في ترسيخ ما تعلمته.", "shortcuts_title": "⌨️ اختصارات لوحة المفاتيح", "shortcut_space": "تشغيل / إيقاف مؤقت", "shortcut_left": "الرجوع 5 ثوانٍ", "shortcut_right": "التقدم 5 ثوانٍ", "faq_title": "الأسئلة الشائعة", "shortcut_f_a_q": "الأسئلة الشائعة", "faq_blackscreen": "شاشة سوداء/بيضاء: يرجى تثبيت أحدث إصدار من WebView2.", "faq_ytdlp": "فشل تنزيل الرابط: يرجى التأكد من تثبيت yt-dlp (pip install yt-dlp)." },
    "he": { "title": "מרכז עזרה", "subtitle": "מדריך מהיר לשימוש ב-ListenMate++", "library_title": "📚 ספריה", "library_desc": "ייבא קבצי שמע מקומיים או הורד שמע דרך קישור (YouTube/Bilibili). לחץ על \"המשך\" כדי להיכנס לסביבת הלמידה.", "workspace_title": "🎧 סביבת למידה", "workspace_desc": "השמע שמע והצג תמלולים. לחץ על כל מילה כדי לקפוץ לחותמת הזמן הזו. בחר טקסט ולחץ על \"הצללה\" כדי לתרגל דיבור. הגדר מקטעי AB כדי לחזור על קטעים קשים.", "speaking_title": "🎤 אימון דיבור", "speaking_desc": "לחץ על \"קרא בקול\" ואמור את משפט ההתייחסות. ה-AI יתמלל את ההקלטה שלך, ישווה מילה במילה וייתן לך ציון הגייה.", "review_title": "📅 משימות חזרה", "review_desc": "המערכת מתזמנת חזרות באופן אוטומטי על בסיס עקומת השכחה של אבנינגהאוס כדי לעזור לך לבסס את מה שלמדת.", "shortcuts_title": "⌨️ קיצורי מקלדת", "shortcut_space": "הפעל / השהה", "shortcut_left": "אחורה 5 שניות", "shortcut_right": "קדימה 5 שניות", "faq_title": "שאלות נפוצות", "shortcut_f_a_q": "שאלות נפוצות", "faq_blackscreen": "מסך שחור/לבן: אנא התקן את זמן הריצה העדכני ביותר של WebView2.", "faq_ytdlp": "הורדת כתובת אתר נכשלה: ודא ש-yt-dlp מותקן (pip install yt-dlp)." }
};

let count = 0;
Object.keys(translations).forEach(locale => {
    const filePath = path.join(localesDir, `${locale}.json`);
    if (fs.existsSync(filePath)) {
        const content = fs.readFileSync(filePath, 'utf8');
        try {
            const data = JSON.parse(content);
            data.help = translations[locale];
            // Write it back with normal 4-space formatting
            fs.writeFileSync(filePath, JSON.stringify(data, null, 4), 'utf8');
            console.log(`Updated ${locale}.json`);
            count++;
        } catch (e) {
            console.error(`Error processing ${locale}.json`, e);
        }
    } else {
        console.warn(`File ${filePath} does not exist`);
    }
});

// Fix en.json faq_ytdlp string if not exists
const enPath = path.join(localesDir, 'en.json');
if (fs.existsSync(enPath)) {
    const content = fs.readFileSync(enPath, 'utf8');
    try {
        const data = JSON.parse(content);
        if (data.help && !data.help.faq_ytdlp) {
            data.help.faq_ytdlp = "URL Download failed: Please make sure yt-dlp is installed (pip install yt-dlp).";
            fs.writeFileSync(enPath, JSON.stringify(data, null, 4), 'utf8');
            console.log(`Added faq_ytdlp to en.json`);
            count++;
        }
    } catch (e) {
        console.error(`Error processing en.json`, e);
    }
}
console.log(`Finished processing ${count} files.`);
