import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const localesDir = path.join(__dirname, '../src/locales');

const patchData = {
    "zh-TW": {
        library: { title: "學習資料庫", subtitle: "管理您的聽力素材和學習記錄", addLocal: "＋ 添加本地文件", importUrl: "🔗 URL 導入", empty: "資料庫還是空的，快去導入一些學習素材吧！", search: "搜索資料...", sort: "排序", sortNewest: "最近添加", sortOldest: "最早加入", sortTitle: "標題 (A-Z)", deleteConfirm: "確定要刪除這段資料嗎？相關複習數據也將被清理。", rename: "重命名資料", renamePlaceholder: "輸入新標題", continue: "繼續學習", lastStudied: "上次學習", duration: "時長", progress: "已學 {{percent}}%", loadFail: "加載音頻失敗: {{error}}", downloadFail: "加載下載文件失敗: {{error}}" },
        urlImport: { title: "🔗 從 URL 導入音頻", subtitle: "支持 YouTube、Bilibili 等 yt-dlp 兼容的鏈接", placeholder: "粘貼 URL，如 https://youtu.be/...", ytdlpMissing: "未檢測到 yt-dlp，請先安裝：", download: "開始下載", downloading: "下載中...", downloading_status: "⏳ 下載中..." },
        speaking: { title: "口語跟讀", subtitle: "跟讀參考原句，AI 評測你的發音準確率", referenceLabel: "參考原句", playRef: "▶️ 播放原音", playing: "🔊 播放中...", autoFetch: "🔄 自動獲取", fetching: "⏳", edit: "✏️ 編輯", startRecord: "🎙 直接朗讀", shadowRead: "🎧 聽一段並跟讀", recording: "錄音中", stopRecord: "⏹ 停止", evaluating: "AI 正在評測...", score: "得分", playback: "回放你的錄音", recognized: "AI 識別到你說的", wordDiff: "逐詞對比", correct: "🟢 正確", missed: "🔴 漏說/錯誤", extra: "🟠 多說", tryAgain: "🔄 再次練習", saveRecording: "💾 保存錄音", tip: "💡 提示：先閱讀並理解參考原句，然後點擊按鈕並大聲朗讀句子。", readyPrompt: "準備好了嗎？點擊按鈕開始跟讀上方的句子", micError: "無法訪問麥克風: {{error}}", evalFail: "評估失敗: {{error}}", start: "開始", end: "結束" },
        review: { title: "複習任務", subtitle: "基於艾賓浩斯記憶曲線的智能複習安排", dueToday: "今日待複習", recentAccuracy: "近期正確率", startReview: "開始今日複習", allDone: "今日複習已完成", nextItem: "下一題", finishReview: "完成複習", retry: "重試", reviewAll: "全量練習", reviewAllDesc: "複習所有已練習的句子，不受時間限制" },
        workspace_v2: { tabs: { segments: "片段", transcript: "字幕", dictation: "聽寫" }, segments_empty: "暫無複讀段。如果在學習過程中遇到長難句，可以通過下方操作建立複讀段：", segments_tip_a: "1. 播放到句子開頭，按A", segments_tip_b: "2. 播放到結尾處，按B", dictation_select_tip: "請先在左側復讀段落列表中選擇一個復讀段落開始聽寫練習。", resume_title: "恢復進度？", resume_desc: "從 {{time}} 繼續？", resume_yes: "恢復", resume_no: "重新開始", empty_material: "請先從資料庫選擇素材", to_library: "前往資料庫", transcribing: "生成字幕中...", model_missing: "未檢測到模型", model_desc: "需要下載模型", download_model: "下載模型", downloading_model: "下載中...", dictation_placeholder: "在此輸入聽到的內容...", dictation_submit: "提交 (Ctrl+Enter)", dictation_score: "得分: {{score}}", dictation_original: "原文: {{text}}", ab_cancel: "取消標記", segment_label: "段落 {{idx}}", loop_infinite: "無限循環", loop_remaining: "剩 {{count}} 次", delete_segment: "刪除此段", adj_start_minus: "開始-1s", adj_start_plus: "開始+1s", adj_end_minus: "結束-1s", adj_end_plus: "結束+1s", dictation_active: "正在聽寫", dictation_submit_btn: "提交", dictation_score_label: "得分", dictation_your_answer: "回答", dictation_original_text: "原文本" }
    },
    "ja": {
        library: { title: "ライブラリ", subtitle: "オーディオ資料と学習記録の管理", addLocal: "＋ ローカルファイルを追加", importUrl: "🔗 URL をインポート", empty: "ライブラリは空です。学習資料をインポートしてください！", search: "資料を検索...", sort: "並べ替え", sortNewest: "最新", sortOldest: "最古", sortTitle: "タイトル(A-Z)", deleteConfirm: "この資料を削除してもよろしいですか？関連する復習データも削除されます。", rename: "名前の変更", renamePlaceholder: "新しいタイトルを入力", continue: "学習を続ける", lastStudied: "前回の学習", duration: "長さ", progress: "{{percent}}% 完了", loadFail: "読み込み失敗: {{error}}", downloadFail: "ダウンロード失敗: {{error}}" },
        urlImport: { title: "🔗 URL からインポート", subtitle: "YouTube、Bilibili、yt-dlp 対応リンクをサポート", placeholder: "URLを貼り付け...", ytdlpMissing: "yt-dlpがインストールされていません:", download: "ダウンロード", downloading: "ダウンロード中...", downloading_status: "⏳ ダウンロード中..." },
        speaking: { title: "スピーキング練習", subtitle: "例文をシャドーイングし、AIの発音評価を取得", referenceLabel: "例文", playRef: "▶️ オリジナルを再生", playing: "🔊 再生中...", autoFetch: "🔄 自動取得", fetching: "⏳", edit: "✏️ 編集", startRecord: "🎙 直接読む", shadowRead: "🎧 聞いてシャドーイング", recording: "録音中", stopRecord: "⏹ 停止", evaluating: "AI 評価中...", score: "スコア", playback: "録音を再生", recognized: "AIの認識結果", wordDiff: "単語ごとの比較", correct: "🟢 正解", missed: "🔴 抜け/間違い", extra: "🟠 余分", tryAgain: "🔄 もう一度", saveRecording: "💾 保存", tip: "💡 ヒント: 例文を理解してからボタンをクリックし、自然な速度で音読してください。", readyPrompt: "準備はいいですか？ボタンをクリックして上の文を読んでください", micError: "マイクにアクセスできません: {{error}}", evalFail: "評価失敗: {{error}}", start: "開始", end: "終了" },
        review: { title: "復習タスク", subtitle: "エビングハウスの忘却曲線に基づいたスマートな復習", dueToday: "今日の復習", recentAccuracy: "最近の正解率", startReview: "今日の復習を始める", allDone: "今日の復習は完了しました", nextItem: "次へ", finishReview: "完了", retry: "再試行", reviewAll: "すべて練習", reviewAllDesc: "時間制限なしで練習済みの文をすべて復習" },
        workspace_v2: { tabs: { segments: "セグメント", transcript: "字幕", dictation: "ディクテーション" }, segments_empty: "セグメントがありません。再生中に以下の操作で作成できます:", segments_tip_a: "1. 文の開始でAを押す", segments_tip_b: "2. 文の終了でBを押す", dictation_select_tip: "左側のリストからセグメントを選択してディクテーションを開始してください。", resume_title: "再開しますか？", resume_desc: "{{time}} から再開しますか？", resume_yes: "再開", resume_no: "最初から", empty_material: "資料を選択してください", to_library: "ライブラリへ", transcribing: "字幕生成中...", model_missing: "モデルがありません", model_desc: "モデルをダウンロードする必要があります", download_model: "ダウンロード", downloading_model: "ダウンロード中...", dictation_placeholder: "聞こえた内容を入力...", dictation_submit: "送信 (Ctrl+Enter)", dictation_score: "スコア: {{score}}", dictation_original: "原文: {{text}}", ab_cancel: "キャンセル", segment_label: "セグメント {{idx}}", loop_infinite: "無限ループ", loop_remaining: "残り {{count}} 回", delete_segment: "削除", adj_start_minus: "開始-1s", adj_start_plus: "開始+1s", adj_end_minus: "終了-1s", adj_end_plus: "終了+1s", dictation_active: "ディクテーション中", dictation_submit_btn: "送信", dictation_score_label: "スコア", dictation_your_answer: "回答", dictation_original_text: "原文" }
    },
    "ko": {
        library: { title: "학습 라이브러리", subtitle: "학습 자료 및 기록 관리", addLocal: "＋ 로컬 파일 추가", importUrl: "🔗 URL 가져오기", empty: "라이브러리가 비어있습니다. 자료를 추가해주세요!", search: "자료 검색...", sort: "정렬", sortNewest: "최신순", sortOldest: "오래된순", sortTitle: "제목순(A-Z)", deleteConfirm: "이 자료를 삭제하시겠습니까? 관련된 복습 데이터도 삭제됩니다.", rename: "이름 변경", renamePlaceholder: "새 제목 입력", continue: "학습 계속하기", lastStudied: "최근 학습일", duration: "길이", progress: "{{percent}}% 완료", loadFail: "로드 실패: {{error}}", downloadFail: "다운로드 실패: {{error}}" },
        urlImport: { title: "🔗 URL에서 오디오 가져오기", subtitle: "YouTube, Bilibili, yt-dlp 호환 링크 지원", placeholder: "URL 붙여넣기...", ytdlpMissing: "yt-dlp를 찾을 수 없습니다:", download: "다운로드 시작", downloading: "다운로드 중...", downloading_status: "⏳ 다운로드 중..." },
        speaking: { title: "말하기 연습", subtitle: "참고 문장을 쉐도잉하고 AI 발음 피드백 받기", referenceLabel: "참고 문장", playRef: "▶️ 원본 재생", playing: "🔊 재생 중...", autoFetch: "🔄 자동 가져오기", fetching: "⏳", edit: "✏️ 편집", startRecord: "🎙 바로 읽기", shadowRead: "🎧 듣고 쉐도잉", recording: "녹음 중", stopRecord: "⏹ 중지", evaluating: "AI 평가 중...", score: "점수", playback: "녹음 재생", recognized: "AI 인식 결과", wordDiff: "단어별 비교", correct: "🟢 정확함", missed: "🔴 누락/오류", extra: "🟠 অতিরিক্ত", tryAgain: "🔄 다시 시작", saveRecording: "💾 저장", tip: "💡 팁: 문장을 이해한 후 자연스러운 속도로 소리내어 읽으세요.", readyPrompt: "준비되셨나요? 버튼을 클릭하고 문장을 읽으세요", micError: "마이크 오류: {{error}}", evalFail: "평가 실패: {{error}}", start: "시작", end: "종료" },
        review: { title: "복습 과제", subtitle: "에빙하우스 망각 곡선 기반 스마트 복습 일정", dueToday: "오늘의 복습", recentAccuracy: "최근 정확도", startReview: "오늘의 복습 시작", allDone: "오늘 복습 완료", nextItem: "다음", finishReview: "완료", retry: "재시도", reviewAll: "전체 연습", reviewAllDesc: "시간 제한 없이 모든 연습한 문장을 복습" },
        workspace_v2: { tabs: { segments: "단락", transcript: "자막", dictation: "받아쓰기" }, segments_empty: "아직 반복 구간이 없습니다. 다음과 같이 생성하세요:", segments_tip_a: "1. 문장 시작 부분에서 A 누르기", segments_tip_b: "2. 문장 끝에서 B 누르기", dictation_select_tip: "받아쓰기를 시작하려면 왼쪽 목록에서 단락을 선택하세요.", resume_title: "진행 상황 복구", resume_desc: "{{time}}부터 계속할까요?", resume_yes: "예", resume_no: "아니요", empty_material: "자료를 선택하세요", to_library: "라이브러리로", transcribing: "자막 생성 중...", model_missing: "모델 없음", model_desc: "다운로드 필요", download_model: "다운로드", downloading_model: "다운로드 중...", dictation_placeholder: "들리는 내용 입력...", dictation_submit: "제출 (Ctrl+Enter)", dictation_score: "점수: {{score}}", dictation_original: "원본: {{text}}", ab_cancel: "취소", segment_label: "단락 {{idx}}", loop_infinite: "무한 반복", loop_remaining: "{{count}}회 남음", delete_segment: "삭제", adj_start_minus: "시작-1s", adj_start_plus: "시작+1s", adj_end_minus: "종료-1s", adj_end_plus: "종료+1s", dictation_active: "받아쓰기 중", dictation_submit_btn: "제출", dictation_score_label: "점수", dictation_your_answer: "내 답변", dictation_original_text: "원본" }
    },
    "ru": {
        library: { title: "Библиотека", subtitle: "Управление аудио материалами и записями", addLocal: "＋ Добавить локальный файл", importUrl: "🔗 Импорт по URL", empty: "Библиотека пуста. Добавьте материалы!", search: "Поиск...", sort: "Сортировка", sortNewest: "Сначала новые", sortOldest: "Сначала старые", sortTitle: "По названию (А-Я)", deleteConfirm: "Вы уверены, что хотите удалить этот материал?", rename: "Переименовать", renamePlaceholder: "Новое название", continue: "Продолжить", lastStudied: "Последнее", duration: "Длительность", progress: "{{percent}}% изучено", loadFail: "Ошибка аудио: {{error}}", downloadFail: "Ошибка загрузки: {{error}}" },
        urlImport: { title: "🔗 Импорт аудио по URL", subtitle: "Поддерживает YouTube, Bilibili и yt-dlp", placeholder: "Вставьте URL...", ytdlpMissing: "yt-dlp не найден:", download: "Скачать", downloading: "Скачивание...", downloading_status: "⏳ Скачивание..." },
        speaking: { title: "Практика речи", subtitle: "Повторяйте предложения и получайте оценку AI", referenceLabel: "Исходное предложение", playRef: "▶️ Слушать оригинал", playing: "🔊 Воспроизведение...", autoFetch: "🔄 Авто-получение", fetching: "⏳", edit: "✏️ Редактировать", startRecord: "🎙 Прочитать вслух", shadowRead: "🎧 Слушать и повторять", recording: "Запись...", stopRecord: "⏹ Стоп", evaluating: "Оценка AI...", score: "Балл", playback: "Слушать себя", recognized: "AI услышал", wordDiff: "Сравнение слов", correct: "🟢 Верно", missed: "🔴 Пропущено/Ошибка", extra: "🟠 Лишнее", tryAgain: "🔄 Еще раз", saveRecording: "💾 Сохранить", tip: "💡 Совет: поймите предложение и прочитайте его вслух.", readyPrompt: "Готовы? Нажмите кнопку и прочитайте предложение", micError: "Ошибка микрофона: {{error}}", evalFail: "Ошибка оценки: {{error}}", start: "Начало", end: "Конец" },
        review: { title: "Задачи на повторение", subtitle: "Умное расписание на основе кривой забывания", dueToday: "Повторить сегодня", recentAccuracy: "Недавняя точность", startReview: "Начать повторение", allDone: "Все повторено на сегодня", nextItem: "Далее", finishReview: "Завершить", retry: "Повторить", reviewAll: "Практиковать все", reviewAllDesc: "Повторение всех предложений без ограничений по времени" },
        workspace_v2: { tabs: { segments: "Фрагменты", transcript: "Субтитры", dictation: "Диктант" }, segments_empty: "Пока нет фрагментов. Создайте их:", segments_tip_a: "1. Старт - нажмите A", segments_tip_b: "2. Конец - нажмите B", dictation_select_tip: "Выберите фрагмент в списке слева, чтобы начать.", resume_title: "Продолжить?", resume_desc: "Продолжить с {{time}}?", resume_yes: "Да", resume_no: "Сначала", empty_material: "Выберите материал", to_library: "В библиотеку", transcribing: "Создание субтитров...", model_missing: "Модель не найдена", model_desc: "Нужно скачать модель", download_model: "Скачать", downloading_model: "Скачивание...", dictation_placeholder: "Введите то, что слышите...", dictation_submit: "Отправить (Ctrl+Enter)", dictation_score: "Балл: {{score}}", dictation_original: "Оригинал: {{text}}", ab_cancel: "Отмена", segment_label: "Фрагмент {{idx}}", loop_infinite: "Бесконечно", loop_remaining: "Осталось {{count}} раз", delete_segment: "Удалить", adj_start_minus: "Начало-1с", adj_start_plus: "Начало+1с", adj_end_minus: "Конец-1с", adj_end_plus: "Конец+1с", dictation_active: "Диктуется", dictation_submit_btn: "Отправить", dictation_score_label: "Балл", dictation_your_answer: "Ваш ответ", dictation_original_text: "Оригинал" }
    },
    "pt": {
        library: { title: "Biblioteca", subtitle: "Gerencie seus materiais e registros", addLocal: "＋ Arquivo Local", importUrl: "🔗 Importar URL", empty: "Biblioteca vazia. Adicione materiais!", search: "Pesquisar...", sort: "Classificar", sortNewest: "Mais recentes", sortOldest: "Mais antigos", sortTitle: "Título (A-Z)", deleteConfirm: "Certeza que deseja excluir?", rename: "Renomear", renamePlaceholder: "Novo título", continue: "Continuar", lastStudied: "Último estudo", duration: "Duração", progress: "{{percent}}% concluído", loadFail: "Falha de áudio: {{error}}", downloadFail: "Falha de download: {{error}}" },
        urlImport: { title: "🔗 Importar de URL", subtitle: "Suporta YouTube, Bilibili e yt-dlp", placeholder: "Cole a URL...", ytdlpMissing: "yt-dlp não encontrado:", download: "Baixar", downloading: "Baixando...", downloading_status: "⏳ Baixando..." },
        speaking: { title: "Prática de Fala", subtitle: "Faça shadowing e obtenha pontuação da IA", referenceLabel: "Frase de Referência", playRef: "▶️ Tocar Original", playing: "🔊 Tocando...", autoFetch: "🔄 Auto-obter", fetching: "⏳", edit: "✏️ Editar", startRecord: "🎙 Ler em voz alta", shadowRead: "🎧 Ouvir e Shadow", recording: "Gravando...", stopRecord: "⏹ Parar", evaluating: "Avaliando...", score: "Pontuação", playback: "Ouvir sua gravação", recognized: "IA entendeu", wordDiff: "Comparação de palavras", correct: "🟢 Correto", missed: "🔴 Faltou/Erro", extra: "🟠 Extra", tryAgain: "🔄 Tentar Novamente", saveRecording: "💾 Salvar", tip: "💡 Dica: Entenda a frase e leia em voz alta naturalmente.", readyPrompt: "Pronto? Clique e leia a frase.", micError: "Erro de microfone: {{error}}", evalFail: "Falha na avaliação: {{error}}", start: "Início", end: "Fim" },
        review: { title: "Revisão", subtitle: "Revisão inteligente (curva de Ebbinghaus)", dueToday: "Para hoje", recentAccuracy: "Precisão recente", startReview: "Iniciar Revisão", allDone: "Tudo revisado hoje", nextItem: "Próximo", finishReview: "Concluir", retry: "Tentar de novo", reviewAll: "Praticar Tudo", reviewAllDesc: "Revise todas as frases sem limite de tempo" },
        workspace_v2: { tabs: { segments: "Trechos", transcript: "Legendas", dictation: "Ditado" }, segments_empty: "Sem trechos ainda. Crie um:", segments_tip_a: "1. No início da frase, pressione A", segments_tip_b: "2. No final, pressione B", dictation_select_tip: "Selecione um trecho à esquerda para começar o ditado.", resume_title: "Retomar?", resume_desc: "Continuar de {{time}}?", resume_yes: "Sim", resume_no: "Reiniciar", empty_material: "Selecione um material", to_library: "Ir para Biblioteca", transcribing: "Gerando legendas...", model_missing: "Modelo ausente", model_desc: "Baixe o modelo", download_model: "Baixar", downloading_model: "Baixando...", dictation_placeholder: "Digite o que ouvir...", dictation_submit: "Enviar (Ctrl+Enter)", dictation_score: "Pontuação: {{score}}", dictation_original: "Original: {{text}}", ab_cancel: "Cancelar", segment_label: "Trecho {{idx}}", loop_infinite: "Infinito", loop_remaining: "{{count}} restantes", delete_segment: "Excluir", adj_start_minus: "Início-1s", adj_start_plus: "Início+1s", adj_end_minus: "Fim-1s", adj_end_plus: "Fim+1s", dictation_active: "Ditando", dictation_submit_btn: "Enviar", dictation_score_label: "Pontuação", dictation_your_answer: "Sua resposta", dictation_original_text: "Original" }
    },
    "es": {
        library: { title: "Biblioteca", subtitle: "Gestiona tus materiales y registros", addLocal: "＋ Añadir Local", importUrl: "🔗 Importar URL", empty: "Biblioteca vacía. ¡Añade materiales!", search: "Buscar...", sort: "Ordenar", sortNewest: "Más recientes", sortOldest: "Más antiguos", sortTitle: "Título (A-Z)", deleteConfirm: "¿Seguro que quieres eliminar esto?", rename: "Renombrar", renamePlaceholder: "Nuevo título", continue: "Continuar", lastStudied: "Último estudio", duration: "Duración", progress: "{{percent}}% completado", loadFail: "Fallo de audio: {{error}}", downloadFail: "Fallo de descarga: {{error}}" },
        urlImport: { title: "🔗 Importar desde URL", subtitle: "Soporta YouTube, Bilibili y yt-dlp", placeholder: "Pegar URL...", ytdlpMissing: "yt-dlp no encontrado:", download: "Descargar", downloading: "Descargando...", downloading_status: "⏳ Descargando..." },
        speaking: { title: "Práctica de Habla", subtitle: "Haz shadowing y obtén puntuación de la IA", referenceLabel: "Frase de Referencia", playRef: "▶️ Reproducir Original", playing: "🔊 Reproduciendo...", autoFetch: "🔄 Auto-obtener", fetching: "⏳", edit: "✏️ Editar", startRecord: "🎙 Leer en voz alta", shadowRead: "🎧 Escuchar y Shadow", recording: "Grabando...", stopRecord: "⏹ Detener", evaluating: "Evaluando...", score: "Puntuación", playback: "Escuchar grabación", recognized: "IA entendió", wordDiff: "Comparación", correct: "🟢 Correcto", missed: "🔴 Falta/Error", extra: "🟠 Extra", tryAgain: "🔄 Reintentar", saveRecording: "💾 Guardar", tip: "💡 Consejo: Entiende la frase y léela en voz alta con naturalidad.", readyPrompt: "¿Listo? Haz clic y lee.", micError: "Error de micrófono: {{error}}", evalFail: "Fallo de evaluación: {{error}}", start: "Inicio", end: "Fin" },
        review: { title: "Revisión", subtitle: "Revisión inteligente (Ebbinghaus)", dueToday: "Para hoy", recentAccuracy: "Precisión reciente", startReview: "Iniciar Revisión de Hoy", allDone: "Todo revisado por hoy", nextItem: "Siguiente", finishReview: "Finalizar", retry: "Reintentar", reviewAll: "Practicar Todo", reviewAllDesc: "Revisa todas las frases sin límite de tiempo" },
        workspace_v2: { tabs: { segments: "Fragmentos", transcript: "Subtítulos", dictation: "Dictado" }, segments_empty: "Aún no hay fragmentos. Créalos:", segments_tip_a: "1. Ve al inicio y pulsa A", segments_tip_b: "2. Ve al final y pulsa B", dictation_select_tip: "Selecciona un fragmento a la izquierda para empezar.", resume_title: "¿Reanudar?", resume_desc: "¿Continuar desde {{time}}?", resume_yes: "Sí", resume_no: "Reiniciar", empty_material: "Selecciona un material", to_library: "Ir a Biblioteca", transcribing: "Generando subtítulos...", model_missing: "Modelo ausente", model_desc: "Descarga el modelo", download_model: "Descargar", downloading_model: "Descargando...", dictation_placeholder: "Escribe lo que escuches...", dictation_submit: "Enviar (Ctrl+Enter)", dictation_score: "Puntuación: {{score}}", dictation_original: "Original: {{text}}", ab_cancel: "Cancelar", segment_label: "Fragmento {{idx}}", loop_infinite: "Infinito", loop_remaining: "{{count}} restantes", delete_segment: "Eliminar", adj_start_minus: "Inicio-1s", adj_start_plus: "Inicio+1s", adj_end_minus: "Fin-1s", adj_end_plus: "Fin+1s", dictation_active: "Dictando", dictation_submit_btn: "Enviar", dictation_score_label: "Puntuación", dictation_your_answer: "Tu respuesta", dictation_original_text: "Original" }
    },
    "fr": {
        library: { title: "Bibliothèque", subtitle: "Gérez vos supports audio et vos enregistrements d'étude", addLocal: "＋ Ajouter le fichier local", importUrl: "🔗 Importer URL", empty: "La bibliothèque est vide. Importez des supports!", search: "Rechercher...", sort: "Trier", sortNewest: "Plus récents", sortOldest: "Plus anciens", sortTitle: "Titre (A-Z)", deleteConfirm: "Êtes-vous sûr de vouloir supprimer?", rename: "Renommer", renamePlaceholder: "Nouveau titre", continue: "Continuer", lastStudied: "Dernière étude", duration: "Durée", progress: "{{percent}}% terminé", loadFail: "Échec audio: {{error}}", downloadFail: "Échec téléchargement: {{error}}" },
        urlImport: { title: "🔗 Importer depuis l'URL", subtitle: "Prend en charge YouTube, Bilibili et yt-dlp", placeholder: "Collez l'URL...", ytdlpMissing: "yt-dlp non trouvé:", download: "Télécharger", downloading: "Téléchargement...", downloading_status: "⏳ Téléchargement..." },
        speaking: { title: "Pratique Orale", subtitle: "Répétez les phrases et obtenez le score de prononciation de l'IA", referenceLabel: "Phrase de Référence", playRef: "▶️ Jouer Original", playing: "🔊 Lecture...", autoFetch: "🔄 Récupération auto", fetching: "⏳", edit: "✏️ Éditer", startRecord: "🎙 Lire à haute voix", shadowRead: "🎧 Écouter et Répéter", recording: "Enregistrement...", stopRecord: "⏹ Arrêter", evaluating: "L'IA évalue...", score: "Score", playback: "Écouter votre enregistrement", recognized: "L'IA a entendu", wordDiff: "Comparaison de mots", correct: "🟢 Correct", missed: "🔴 Manqué/Faux", extra: "🟠 Extra", tryAgain: "🔄 Réessayer", saveRecording: "💾 Sauvegarder", tip: "💡 Astuce: Comprenez la phrase puis lisez-la naturellement.", readyPrompt: "Prêt? Cliquez et lisez la phrase.", micError: "Erreur micro: {{error}}", evalFail: "Échec évaluation: {{error}}", start: "Début", end: "Fin" },
        review: { title: "Tâches de révision", subtitle: "Calendrier de révision intelligent (courbe d'Ebbinghaus)", dueToday: "À réviser aujourd'hui", recentAccuracy: "Précision récente", startReview: "Commencer la révision", allDone: "Révision terminée pour aujourd'hui", nextItem: "Suivant", finishReview: "Terminer", retry: "Réessayer", reviewAll: "Tout Pratiquer", reviewAllDesc: "Révisez toutes les phrases sans limite de temps" },
        workspace_v2: { tabs: { segments: "Segments", transcript: "Sous-titres", dictation: "Dictée" }, segments_empty: "Pas encore de segments. Créez-en un:", segments_tip_a: "1. Au début de la phrase, appuyez sur A", segments_tip_b: "2. À la fin, appuyez sur B", dictation_select_tip: "Sélectionnez un segment à gauche pour commencer.", resume_title: "Reprendre?", resume_desc: "Continuer à partir de {{time}}?", resume_yes: "Oui", resume_no: "Recommencer", empty_material: "Sélectionnez un fichier", to_library: "Aller à la bibliothèque", transcribing: "Génération de sous-titres...", model_missing: "Modèle manquant", model_desc: "Veuillez télécharger le modèle", download_model: "Télécharger", downloading_model: "Téléchargement...", dictation_placeholder: "Tapez ce que vous entendez...", dictation_submit: "Soumettre (Ctrl+Enter)", dictation_score: "Score: {{score}}", dictation_original: "Original: {{text}}", ab_cancel: "Annuler", segment_label: "Segment {{idx}}", loop_infinite: "Infini", loop_remaining: "{{count}} restants", delete_segment: "Supprimer", adj_start_minus: "Début-1s", adj_start_plus: "Début+1s", adj_end_minus: "Fin-1s", adj_end_plus: "Fin+1s", dictation_active: "En dictée", dictation_submit_btn: "Soumettre", dictation_score_label: "Score", dictation_your_answer: "Votre réponse", dictation_original_text: "Original" }
    },
    "de": {
        library: { title: "Bibliothek", subtitle: "Verwalten Sie Ihre Materialien und Aufzeichnungen", addLocal: "＋ Lokale Datei hinzufügen", importUrl: "🔗 URL importieren", empty: "Die Bibliothek ist leer. Importieren Sie Materialien!", search: "Suchen...", sort: "Sortieren", sortNewest: "Neueste", sortOldest: "Älteste", sortTitle: "Titel (A-Z)", deleteConfirm: "Sind Sie sicher, dass Sie dies löschen möchten?", rename: "Umbenennen", renamePlaceholder: "Neuer Titel", continue: "Weiterlernen", lastStudied: "Zuletzt gelernt", duration: "Dauer", progress: "{{percent}}% abgeschlossen", loadFail: "Audio-Fehler: {{error}}", downloadFail: "Download-Fehler: {{error}}" },
        urlImport: { title: "🔗 Audio von URL importieren", subtitle: "Unterstützt YouTube, Bilibili und yt-dlp", placeholder: "URL einfügen...", ytdlpMissing: "yt-dlp nicht gefunden:", download: "Herunterladen", downloading: "Lade herunter...", downloading_status: "⏳ Laden..." },
        speaking: { title: "Sprechübung", subtitle: "Sätze wiederholen und KI-Aussprache-Feedback erhalten", referenceLabel: "Referenzsatz", playRef: "▶️ Original abspielen", playing: "🔊 Spielt ab...", autoFetch: "🔄 Auto-Abruf", fetching: "⏳", edit: "✏️ Bearbeiten", startRecord: "🎙 Laut vorlesen", shadowRead: "🎧 Hören & Shadowing", recording: "Nimmt auf...", stopRecord: "⏹ Stopp", evaluating: "KI wertet aus...", score: "Mittelwert", playback: "Aufnahme abspielen", recognized: "KI hörte", wordDiff: "Wortvergleich", correct: "🟢 Richtig", missed: "🔴 Verpasst/Falsch", extra: "🟠 Extra", tryAgain: "🔄 Noch einmal", saveRecording: "💾 Speichern", tip: "💡 Tipp: Verstehen Sie den Satz und lesen Sie ihn natürlich ab.", readyPrompt: "Bereit? Klicken und vorlesen.", micError: "Mikrofon-Fehler: {{error}}", evalFail: "Bewertungsfehler: {{error}}", start: "Start", end: "Ende" },
        review: { title: "Wiederholung", subtitle: "Intelligente Wiederholung (Ebbinghaus)", dueToday: "Heute fällig", recentAccuracy: "Letzte Genauigkeit", startReview: "Heutige Wiederholung starten", allDone: "Alles für heute wiederholt", nextItem: "Nächste", finishReview: "Beenden", retry: "Erneut", reviewAll: "Alles üben", reviewAllDesc: "Wiederholen Sie alle Sätze ohne Zeitlimit" },
        workspace_v2: { tabs: { segments: "Auswahl", transcript: "Untertitel", dictation: "Diktat" }, segments_empty: "Noch keine Auswahl. Erstellen Sie eine:", segments_tip_a: "1. Am Satzanfang A drücken", segments_tip_b: "2. Am Ende B drücken", dictation_select_tip: "Wählen Sie ein Segment auf der linken Seite aus, um zu beginnen.", resume_title: "Fortsetzen?", resume_desc: "Von {{time}} fortsetzen?", resume_yes: "Ja", resume_no: "Neustart", empty_material: "Wählen Sie eine Datei", to_library: "Zur Bibliothek", transcribing: "Untertitel generieren...", model_missing: "KI-Modell fehlt", model_desc: "Modell herunterladen", download_model: "Herunterladen", downloading_model: "Lade herunter...", dictation_placeholder: "Tippen Sie, was Sie hören...", dictation_submit: "Senden (Ctrl+Enter)", dictation_score: "Mittelwert: {{score}}", dictation_original: "Original: {{text}}", ab_cancel: "Abbrechen", segment_label: "Segment {{idx}}", loop_infinite: "Unendlich", loop_remaining: "Noch {{count}} Mal", delete_segment: "Löschen", adj_start_minus: "Start-1s", adj_start_plus: "Start+1s", adj_end_minus: "Ende-1s", adj_end_plus: "Ende+1s", dictation_active: "Diktieren", dictation_submit_btn: "Senden", dictation_score_label: "Mittelwert", dictation_your_answer: "Ihre Antwort", dictation_original_text: "Original" }
    },
    "ar": {
        library: { title: "المكتبة", subtitle: "إدارة مواد التعلم الخاصة بك", addLocal: "＋ إضافة ملف محلي", importUrl: "🔗 استيراد عبر الرابط", empty: "المكتبة فارغة. قم باستيراد المواد!", search: "البحث في المواد...", sort: "فرز", sortNewest: "الأحدث", sortOldest: "الأقدم", sortTitle: "العنوان", deleteConfirm: "هل أنت متأكد من الحذف؟", rename: "إعادة تسمية", renamePlaceholder: "العنوان الجديد", continue: "متابعة الدراسة", lastStudied: "آخر دراسة:", duration: "المدة:", progress: "تمت دراسة {{percent}}%", loadFail: "فشل تحميل الصوت: {{error}}", downloadFail: "فشل التنزيل: {{error}}" },
        urlImport: { title: "🔗 استيراد من رابط", subtitle: "يدعم يوتيوب ومواقع yt-dlp", placeholder: "الصق الرابط...", ytdlpMissing: "yt-dlp غير متوفر:", download: "تنزيل", downloading: "جاري التنزيل...", downloading_status: "⏳ جاري التنزيل..." },
        speaking: { title: "ممارسة التحدث", subtitle: "اقرأ الجمل واحصل على تقييم نطق الذكاء الاصطناعي", referenceLabel: "الجملة المرجعية", playRef: "▶️ تشغيل الأصل", playing: "🔊 جاري التشغيل...", autoFetch: "🔄 جلب تلقائي", fetching: "⏳", edit: "✏️ تعديل", startRecord: "🎙 قراءة بصوت عالٍ", shadowRead: "🎧 استماع وقراءة", recording: "جاري التسجيل...", stopRecord: "⏹ إيقاف", evaluating: "يقوم الذكاء الاصطناعي بالتقييم...", score: "الدرجة", playback: "تشغيل تسجيلك", recognized: "تعرف الذكاء الاصطناعي", wordDiff: "مقارنة الكلمات", correct: "🟢 صحيح", missed: "🔴 خطأ/مفقود", extra: "🟠 إضافي", tryAgain: "🔄 حاول مرة أخرى", saveRecording: "💾 حفظ التسجيل", tip: "💡 نصيحة: افهم الجملة واقرأها بشكل طبيعي.", readyPrompt: "هل أنت مستعد؟ انقر لقراءة الجملة أعلاه.", micError: "خطأ في الميكروفون: {{error}}", evalFail: "فشل التقييم: {{error}}", start: "بداية", end: "نهاية" },
        review: { title: "مهام المراجعة", subtitle: "جدول مراجعة ذكي (منحنى إبنجهاوس)", dueToday: "للمراجعة اليوم", recentAccuracy: "الدقة الحديثة", startReview: "بدء مراجعة اليوم", allDone: "تم الانتهاء من المراجعة اليوم", nextItem: "التالي", finishReview: "إنهاء", retry: "إعادة المحاولة", reviewAll: "ممارسة الكل", reviewAllDesc: "راجع جميع الجمل بدون قيود زمنية" },
        workspace_v2: { tabs: { segments: "المقاطع", transcript: "الترجمة", dictation: "إملاء" }, segments_empty: "لا توجد مقاطع. قم بإنشائها:", segments_tip_a: "1. اضغط A عند البداية", segments_tip_b: "2. اضغط B عند النهاية", dictation_select_tip: "حدد مقطعًا للبدء في الإملاء.", resume_title: "استئناف؟", resume_desc: "متابعة من {{time}}؟", resume_yes: "نعم", resume_no: "البدء من جديد", empty_material: "الرجاء اختيار ملف", to_library: "الذهاب للمكتبة", transcribing: "جاري إنشاء الترجمة...", model_missing: "النموذج مفقود", model_desc: "يرجى تنزيل النموذج", download_model: "تنزيل", downloading_model: "جاري التنزيل...", dictation_placeholder: "اكتب ما تسمعه...", dictation_submit: "إرسال (Ctrl+Enter)", dictation_score: "الدرجة: {{score}}", dictation_original: "الأصل: {{text}}", ab_cancel: "إلغاء المقطع", segment_label: "مقطع {{idx}}", loop_infinite: "تكرار مستمر", loop_remaining: "متبقي {{count}}", delete_segment: "حذف المقطع", adj_start_minus: "بداية-1ث", adj_start_plus: "بداية+1ث", adj_end_minus: "نهاية-1ث", adj_end_plus: "نهاية+1ث", dictation_active: "في الإملاء", dictation_submit_btn: "إرسال التقييم", dictation_score_label: "الدرجة", dictation_your_answer: "إجابتك", dictation_original_text: "النص الأصلي" }
    },
    "he": {
        library: { title: "ספרייה", subtitle: "נהל חומרי למידה ורשומות", addLocal: "＋ הוסף קובץ מקומי", importUrl: "🔗 ייבוא כתובת URL", empty: "הספרייה ריקה. הוסף חומרים!", search: "חיפוש חומרים...", sort: "מיון", sortNewest: "הכי חדש", sortOldest: "הכי ישן", sortTitle: "כותרת (A-Z)", deleteConfirm: "האם אתה בטוח שברצונך למחוק מחיקה זו?", rename: "שנה שם", renamePlaceholder: "שם חדש", continue: "המשך למידה", lastStudied: "נלמד לאחרונה", duration: "משך", progress: "{{percent}}% הוסלמו", loadFail: "שגיאת שמע: {{error}}", downloadFail: "שגיאת הורדה: {{error}}" },
        urlImport: { title: "🔗 ייבוא מ־URL", subtitle: "תומך ב־YouTube, Bilibili", placeholder: "הדבק כתובת...", ytdlpMissing: "yt-dlp אינו מותקן:", download: "הורד", downloading: "מוריד...", downloading_status: "⏳ מוריד..." },
        speaking: { title: "אימון דיבור", subtitle: "קרא בקול וקבל דירוג של בינה מלאכותית", referenceLabel: "משפט ייחוס", playRef: "▶️ השמע למקור", playing: "🔊 מנגן...", autoFetch: "🔄 הבא אוטומטית", fetching: "⏳", edit: "✏️ ערוך", startRecord: "🎙 קרא בקול", shadowRead: "🎧 שמע וקרא", recording: "מקליט...", stopRecord: "⏹ עצור", evaluating: "AI מעריך...", score: "ציון", playback: "האזן שוב", recognized: "AI זיהה", wordDiff: "השוואה", correct: "🟢 נכון", missed: "🔴 פספס/טעות", extra: "🟠 עודף", tryAgain: "🔄 נסה שוב", saveRecording: "💾 שמור", tip: "💡 טיפ: הבן את המשפט וקרא בקול טבעי.", readyPrompt: "מוכן? לחץ וקרא.", micError: "שגיאת מיקרופון: {{error}}", evalFail: "שגיאת הערכה: {{error}}", start: "התחלה", end: "סיום" },
        review: { title: "משימות חזרה", subtitle: "מערכת חזרה חכמה (עקומת אבינגהאוס)", dueToday: "לתרגול היום", recentAccuracy: "דיוק אחרון", startReview: "התחל חזרת היום", allDone: "הכל נעשה להיום", nextItem: "הבא", finishReview: "סיום", retry: "נסה שוב", reviewAll: "תרגל הכל", reviewAllDesc: "חזור על כל המשפטים ללא הגבלת זמן" },
        workspace_v2: { tabs: { segments: "מקטעים", transcript: "כתוביות", dictation: "הכתבה" }, segments_empty: "אין מקטעים. צור אותם:", segments_tip_a: "1. תחילת המשפט חץ A", segments_tip_b: "2. סוף המשפט חץ B", dictation_select_tip: "בחר מקטע להתחלת הכתבה.", resume_title: "לחדש?", resume_desc: "המשך מ-{{time}}?", resume_yes: "כן", resume_no: "התחל מחדש", empty_material: "בחר חומר למידה", to_library: "לך לספרייה", transcribing: "יוצר כתוביות...", model_missing: "חסר מודל", model_desc: "הורד מודל לזיהוי שפה", download_model: "הורד", downloading_model: "מוריד...", dictation_placeholder: "הקלד מה שאתה שומע...", dictation_submit: "שליחה (Ctrl+Enter)", dictation_score: "ציון: {{score}}", dictation_original: "מקור: {{text}}", ab_cancel: "בטל מקטע", segment_label: "מקטע {{idx}}", loop_infinite: "חזרות אינסופיות", loop_remaining: "עוד {{count}}", delete_segment: "מחק מקטע", adj_start_minus: "התחלה-1ש", adj_start_plus: "התחלה+1ש", adj_end_minus: "סיום-1ש", adj_end_plus: "סיום+1ש", dictation_active: "מכתיב", dictation_submit_btn: "שליחה", dictation_score_label: "ציון", dictation_your_answer: "התשובה שלך", dictation_original_text: "מקור" }
    }
};

let count = 0;
Object.keys(patchData).forEach(locale => {
    const filePath = path.join(localesDir, `${locale}.json`);
    if (fs.existsSync(filePath)) {
        const content = fs.readFileSync(filePath, 'utf8');
        try {
            const data = JSON.parse(content);
            const patch = patchData[locale];

            // Merge main sections
            ["library", "urlImport", "speaking", "review"].forEach(section => {
                data[section] = { ...(data[section] || {}), ...patch[section] };
            });

            // Merge workspace_v2
            if (!data.workspace_v2) data.workspace_v2 = {};
            data.workspace_v2 = { ...data.workspace_v2, ...patch.workspace_v2 };

            fs.writeFileSync(filePath, JSON.stringify(data, null, 4), 'utf8');
            console.log(`Updated ${locale}.json`);
            count++;
        } catch (e) {
            console.error(`Error processing ${locale}.json`, e);
        }
    } else {
        console.warn(`File ${filePath} does not exist`);
    }
});
console.log(`Finished processing ${count} files.`);
